"""Add salary table

Revision ID: 22b18aaf4cb1
Revises: e485a629a690
Create Date: 2026-08-28 14:48:17.731861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b18aaf4cb1'
down_revision = 'e485a629a690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salaries',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('salary_month', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salaries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salaries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salaries_user_id'))
        batch_op.drop_index(batch_op.f('ix_salaries_organization_id'))

    op.drop_table('salaries')
    # ### end Alembic commands ###
