"""Add Group models

Revision ID: 44e84d1a102c
Revises: add395ea9863
Create Date: 2026-09-29 18:50:59.970279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e84d1a102c'
down_revision = 'add395ea9863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text('(en)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text('(en)'))

    # ### end Alembic commands ###
