"""Add super_admin role and permissions

Revision ID: a9ae3fc36efa
Revises: 9f1a2c7d3e4b
Create Date: 2026-09-14 17:11:41.938368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ae3fc36efa'
down_revision = '9f1a2c7d3e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reset_requested_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_requested_at')
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
