"""Add Group models and Expense status/approved_by fields

Revision ID: add395ea9863
Revises: a9ae3fc36efa
Create Date: 2026-09-29 18:06:15.580779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add395ea9863'
down_revision = 'a9ae3fc36efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='approved'))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_expense_approved_by_user', 'users', ['approved_by_id'], ['id'])

    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text('(en)'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
